// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Xnzq-wOtadP5ARBtGCEIAKqSKRJbgDY',
    appId: '1:752328696942:web:967e1327d721ae00df327f',
    messagingSenderId: '752328696942',
    projectId: 'fir-81d33',
    authDomain: 'fir-81d33.firebaseapp.com',
    storageBucket: 'fir-81d33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlTzSWxD6feXXdvaMXqVGQ3rnIbTaxlbw',
    appId: '1:752328696942:android:aa2f47206bb1f44edf327f',
    messagingSenderId: '752328696942',
    projectId: 'fir-81d33',
    storageBucket: 'fir-81d33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI9xsBZYWkk4_O7vCp0Wfkx0UOcatA_gE',
    appId: '1:752328696942:ios:48793800978fbf47df327f',
    messagingSenderId: '752328696942',
    projectId: 'fir-81d33',
    storageBucket: 'fir-81d33.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI9xsBZYWkk4_O7vCp0Wfkx0UOcatA_gE',
    appId: '1:752328696942:ios:48793800978fbf47df327f',
    messagingSenderId: '752328696942',
    projectId: 'fir-81d33',
    storageBucket: 'fir-81d33.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7Xnzq-wOtadP5ARBtGCEIAKqSKRJbgDY',
    appId: '1:752328696942:web:cf37c67434109055df327f',
    messagingSenderId: '752328696942',
    projectId: 'fir-81d33',
    authDomain: 'fir-81d33.firebaseapp.com',
    storageBucket: 'fir-81d33.appspot.com',
  );
}
